---
# tasks file for apache2
- name: Install web components + VIM + WGET
  apt: name={{item}} state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - vim
    - wget
    - default-jre

- name: Ensure modd_wsgi is enabled
  apache2_module: state=present name=wsgi
  notify: restart apache2

- name: Desactivate default apache site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2

- name: Ensure apache2 is started and comes up when server was rebooted
  service: name=apache2 state=started enabled=yes

