---
# tasks file for nginx
- name: with_dict
  debug:
    msg: "{{ item.key }} - {{ item.value }}"
  with_dict: "{{ sites }}"

- name: Install nginx
  apt: name=nginx state=present update_cache=yes

- name: nginx loadbalancer configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{item.key}} mode=0644
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: Desactivate default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: activate  nginx site
  file: src=/etc/nginx/sites-available/{{item.key}} dest=/etc/nginx/sites-enabled/{{item.key}} state=link
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: Ensure nginx is started and comes up when server was rebooted
  service: name=nginx state=started enabled=yes
