---
- name: Install tools + VIM
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - net-tools
    - python-mysqldb 
    - vim

- name: Install mysql-server
  apt: name=mysql-server state=present update_cache=yes

- name: Mysql need to listen on all interface
  lineinfile: dest=/etc/mysql/mariadb.conf.d/50-server.cnf regexp=^bind-address 
                line="bind-address = {{ansible_eth0.ipv4.address}}"
  notify: restart mysql

- name: Ensure mysql is started and comes up when server was rebooted
  service: name=mysql state=started enabled=yes

- name: Create  DB 
  mysql_db: name={{db_name}} state=present 

- name: Create user 
# Les variables sont définies dans default et dans le playbook database.yml
# Celles definies dans le playbook sont prioriraires. 
  mysql_user: name={{db_user_name}} password={{db_user_password}} priv={{db_name}}.*:ALL host='{{db_user_host}}' state=present