---
- name: Install tools
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - net-tools
    - python-mysqldb 

- name: Install mysql-server
  apt: name=mysql-server state=present update_cache=yes

- name: Mysql need to listen on all interface
  lineinfile: dest=/etc/mysql/mariadb.conf.d/50-server.cnf regexp=^bind-address 
                line="bind-address = {{ansible_eth0.ipv4.address}}"
  notify: restart mysql

- name: Ensure mysql is started and comes up when server was rebooted
  service: name=mysql state=started enabled=yes

- name: Create demo DB 
  mysql_db: name=demo state=present 

- name: Create user demo
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present