---
# Bring stack down 
- hosts: loadbalancer
  tasks:
    - services: name=nginx state=stopped
    - wait_for: port=80 state=drained

- hosts: webserver
  tasks:
    - services: name=apache2 state=stopped
    - wait_for: port=80 state=stopped

# Restart mysql_db
- hosts: database
  tasks:
    - services: name=mysql state=restarted
    - wait_for: port=3306 state=restarted

# Bring stack up 
- hosts: webserver
  tasks:
    - services: name=apache2 state=started
    - wait_for: port=80 timeout=1

- hosts: loadbalancer
  tasks:
    - services: name=nginx state=started
    - wait_for: port=80 timeout=1